# This file was generated by GoReleaser. DO NOT EDIT.
cask "awesome-directories" do
  name "awesome-directories"
  desc "CLI tool for awesome-directories.com - Discover directories for your SaaS"
  homepage "https://awesome-directories.com"
  version "1.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awesome-directories"

  on_macos do
    on_intel do
      url "https://github.com/awesome-directories/cli/releases/download/v#{version}/cli_darwin_amd64.tar.gz"
      sha256 "b46f808c00c3750074ceedd4e5cfe808611a1a7af57112cb845f3bdc50a63273"
    end
    on_arm do
      url "https://github.com/awesome-directories/cli/releases/download/v#{version}/cli_darwin_arm64.tar.gz"
      sha256 "1da119a72555d3a6d110bd879d660d86dd0f129aad9ab49e036ae75cf93d0730"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/awesome-directories/cli/releases/download/v#{version}/cli_linux_amd64.tar.gz"
      sha256 "bd1276e8e1d7c9aaa7f4c39ec04eeb2998cc5bb8dd887b350c16c3ae8c9a1d80"
    end
    on_arm do
      url "https://github.com/awesome-directories/cli/releases/download/v#{version}/cli_linux_arm64.tar.gz"
      sha256 "365e02b79b1c105824a37c6bb793d98e899b9efb1cbcb109dff66a78cca13d26"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/awesome-directories"]
    end
  end

  # No zap stanza required
end
