# This file was generated by GoReleaser. DO NOT EDIT.
cask "awesome-directories" do
  name "awesome-directories"
  desc "CLI tool for awesome-directories.com - Discover directories for your SaaS"
  homepage "https://awesome-directories.com"
  version "1.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awesome-directories"
  bash_completion "./completions/awesome-directories.bash"
  zsh_completion "./completions/awesome-directories.zsh"
  fish_completion "./completions/awesome-directories.fish"

  on_macos do
    on_intel do
      url "https://github.com/awesome-directories/cli/releases/download/v#{version}/cli_darwin_amd64.tar.gz"
      sha256 "15f97ec02553bd6f8febcdb4bd64f2d363ffeb6702b24808eb6252368b18dfdb"
    end
    on_arm do
      url "https://github.com/awesome-directories/cli/releases/download/v#{version}/cli_darwin_arm64.tar.gz"
      sha256 "cdf672763b763b55b5c9a89c1b0faee6ef453df09ebada7a9b704b19fb3ba104"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/awesome-directories/cli/releases/download/v#{version}/cli_linux_amd64.tar.gz"
      sha256 "70d16fa171ad82a690c1c4c4ba43de237701b4827bc3a07ee5209adda1fa93b5"
    end
    on_arm do
      url "https://github.com/awesome-directories/cli/releases/download/v#{version}/cli_linux_arm64.tar.gz"
      sha256 "9ce44abe6cf44dec2224a131842af24800b6bd04769049b692174e7ad7b2e0c6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/awesome-directories"]
    end
  end

  # No zap stanza required
end
