# This file was generated by GoReleaser. DO NOT EDIT.
cask "awesome-directories" do
  name "awesome-directories"
  desc "CLI tool for awesome-directories.com - Discover directories for your SaaS"
  homepage "https://awesome-directories.com"
  version "1.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awesome-directories"

  on_macos do
    on_intel do
      url "https://github.com/awesome-directories/cli/releases/download/v#{version}/cli_darwin_amd64.tar.gz"
      sha256 "d9ca4c1c62f78cc6a58ba2a0bf792587fb7186bb8de3954263f22f12aa6b04a7"
    end
    on_arm do
      url "https://github.com/awesome-directories/cli/releases/download/v#{version}/cli_darwin_arm64.tar.gz"
      sha256 "0b4a8c9108806b73220e04d0f6de1ff2506cbb10d5bb0b174ac4d407b957be1e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/awesome-directories/cli/releases/download/v#{version}/cli_linux_amd64.tar.gz"
      sha256 "05f90f00ca14ce28295f92ec79414014b7caf2d99504884eb23f9b9a70b4be6e"
    end
    on_arm do
      url "https://github.com/awesome-directories/cli/releases/download/v#{version}/cli_linux_arm64.tar.gz"
      sha256 "05e4b31210af5038710b357d8bf5d4cbd3da533b6d5f598f6cee8476780fa4a6"
    end
  end

  # No zap stanza required
end
